# Generated by Django 2.0.7 on 2018-07-18 19:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import stylemaster.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabconsumption', models.CharField(max_length=20)),
                ('fabquality', models.CharField(max_length=20)),
                ('fabwidth', models.CharField(max_length=10)),
                ('fabunit', models.CharField(max_length=5)),
                ('consumption', models.DecimalField(decimal_places=5, max_digits=12)),
                ('fabrate', models.DecimalField(decimal_places=5, max_digits=12)),
                ('trims', models.CharField(max_length=20)),
                ('trimquality', models.CharField(max_length=20)),
                ('trimspecific', models.CharField(max_length=10)),
                ('trimunit', models.CharField(max_length=5)),
                ('trimconsumption', models.DecimalField(decimal_places=5, max_digits=12)),
                ('trimrate', models.DecimalField(decimal_places=5, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_grp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_no', models.IntegerField(default=stylemaster.models.Fabric.number, unique=True)),
                ('quality', models.CharField(blank=True, max_length=20, null=True)),
                ('composition', models.CharField(max_length=30)),
                ('weave', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.CharField(blank=True, max_length=5, null=True)),
                ('construction', models.CharField(max_length=10)),
                ('types', models.CharField(blank=True, max_length=50, null=True)),
                ('fabric_code', models.CharField(choices=[('Fabric00001', 'Fabric00001'), ('Fabric00002', 'Fabric00002')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FactoryMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_mrchant', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PDMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_mrchant', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_mrchant', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_no', models.IntegerField(default=stylemaster.models.Sample.number, unique=True)),
                ('pch', models.CharField(max_length=10)),
                ('style', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=2500)),
                ('sketch', models.FileField(upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Stylemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_no', models.IntegerField(default=stylemaster.models.Stylemaster.number, unique=True)),
                ('style', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('item_group', models.CharField(max_length=100)),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
                ('responsible', models.CharField(max_length=100)),
                ('product_designer', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_person', models.CharField(max_length=100)),
                ('basic_uom', models.CharField(max_length=100)),
                ('alt_uom', models.CharField(blank=True, max_length=100, null=True)),
                ('conversion_factor', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(max_length=100)),
                ('sales_price', models.CharField(max_length=100)),
                ('sale_price_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('buying_house_commission', models.CharField(blank=True, max_length=100, null=True)),
                ('licence', models.CharField(blank=True, max_length=100, null=True)),
                ('national_dbk', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7, null=True)),
                ('rosl_group', models.CharField(blank=True, max_length=100, null=True)),
                ('propertys', models.CharField(blank=True, max_length=100, null=True)),
                ('order_confirmation_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date')),
                ('pcd', models.DateField(blank=True, null=True)),
                ('ex_factory_date', models.DateField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylemaster.Approver')),
                ('custom_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stylemaster.CustomGroup')),
                ('factory_merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stylemaster.FactoryMerchant')),
                ('item_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylemaster.Sample')),
                ('pd_merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stylemaster.PDMerchant')),
                ('production_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylemaster.ProductionMerchant')),
            ],
        ),
        migrations.CreateModel(
            name='Trims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim_no', models.IntegerField(default=stylemaster.models.Trims.number, unique=True)),
                ('quality', models.CharField(blank=True, max_length=20, null=True)),
                ('composition', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=5)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('construction', models.CharField(max_length=10)),
                ('types', models.CharField(blank=True, max_length=50, null=True)),
                ('trim_code', models.CharField(choices=[('Trim00001', 'Trim00001'), ('Trim00002', 'Trim00002')], max_length=10)),
                ('trim_item_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylemaster.Stylemaster')),
            ],
        ),
        migrations.AddField(
            model_name='fabric',
            name='fabric_item_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylemaster.Stylemaster'),
        ),
        migrations.AddField(
            model_name='bom',
            name='item_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylemaster.Stylemaster'),
        ),
    ]
